### ISSUE TITLE
Not printing the items for the list in twig

### ISSUE THREAD

**Issue by 05K4R1N** [drupal-up/drupalup_controller#1]
Hi here I 'll show you the issue that i have now 
![190418_3](https://user-images.githubusercontent.com/5255678/39062104-7a13fa46-4494-11e8-9f34-747df19aa6e3.png)

The code is exactly the same as you have!

**Comment by 05K4R1N** [comment]
Clearly as you can see the for is working but its not printing anything... and idk why :(

**Comment by flesheater** [comment]
Hi Oscar, 
I just git cloned the module from this repo to a Drupal instance on which it has never been.
Then I just activated the module and it just works when I go under /drupalup/articles

<img width="605" alt="screen shot 2018-04-20 at 18 33 36" src="https://user-images.githubusercontent.com/1736402/39062924-89d462d8-44c9-11e8-8f6d-15a793e84f26.png">

**Comment by flesheater** [comment]
Are you sure you don't have two modules (the module you are trying yourself) and the module downloaded from here, that are declaring the same root ? Have you cleared the cache ? Please send me the content of your controller and of your twig files.

**Comment by 05K4R1N** [comment]
I dont know whnat to say :(  it was cache :( ... damn  i feel bad about this.. i though that the comands:
drupal router rebuild
drush8 cache-build
 was clearing the cache and it wasnt.... glad that its showing... i went to the configuration admin to clear cache in Performance... 

If I am wrong bro.. could you tell me please which is the command for clearing cache by command line?

**Comment by 05K4R1N** [comment]
Working now!
![foto](https://user-images.githubusercontent.com/5255678/39067991-be5496b6-44a8-11e8-9194-0d504989eaa0.png)

**Comment by 05K4R1N** [comment]
Hi i've found toe correct command in drupal console for clearing cache
>> drupal cr all

My apologize dude! :(

**Comment by flesheater** [comment]
No problem. It is admirable that you continued to try even though there was a problem. 
Exactly. The way to clear the cache with drupal console is 

`drupal cr all`

stands for cache rebuild. On the other hand to do it with the help of Drush it is quite similar:
`drush cr`

Cheers and good luck, and don't forget to have fun with drupal module development ;)

**Comment by 05K4R1N** [comment]
Thank you very much dude! I got another problem now... could you  check the other issue... i've already posted it. :( need help

**Comment by 05K4R1N** [comment]
Already sovled! Thanks anyway!
